### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-2-infografia-Ariadnamonserrat10#1]
![Proceso de la construccion del conocimiento](https://user-images.githubusercontent.com/112223282/188527171-1683c1ef-6ffa-4377-ac4c-62eda3009a33.png)

Ariadna Monserrat López Aparicio
1BS

**Comment by AmeliReyesHernandez** [comment]
18.8 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
